### ISSUE TITLE
The player can get stuck behind decorations if they die, are thrusted inside of the decoration, and then respawn

### ISSUE THREAD

**Issue by EmeraldCoasttt** [OrdinaryMagician/swwmgz_m#12]
This bug is reproducable consistently by killing yourself with the hellblazer against this barrel in plutonia map 1
The player can not move or jump. they are trapped completely
![Screenshot_Doom_20210307_103920](https://user-images.githubusercontent.com/72110482/110250688-7354e280-7f31-11eb-943e-562d2806426d.png)

**Comment by OrdinaryMagician** [comment]
This is a vanilla issue and not the mod's fault, but can be worked around. I'll look into it.
