### ISSUE TITLE
Chex key classes are being replaced by Doom key classes

### ISSUE THREAD

**Issue by Iggjarjuk** [OrdinaryMagician/swwmgz_m#13]
Thanks for all the great work, I'm having a blast with this mod!

I figured you'd want to know that there's a compatibility issue with Chex Quest: SWWM's scripted key replacement seems to be changing the Chex Quest keys' classes to the standard Doom keys' classes (for example, a "ChexBlueCard" becomes a regular old "BlueCard", which isn't very useful on Chex maps).

No biggie, though... it's easy enough to work around the issue. Just wanted to let you know.

Thanks again

**Comment by OrdinaryMagician** [comment]
The mod is 100% not compatible with chex quest.
