### ISSUE TITLE
[Question] Puntzer and similar weapons not implemented?

### ISSUE THREAD

**Issue by fleurc** [OrdinaryMagician/swwmgz_m#14]
These red cubes with the name of the weapons keep appearing however there is nothing to be done about them. Are these unlockable weapons? Or are they simply left-overs from development?

**Comment by OrdinaryMagician** [comment]
The mod is still in development. The message of "not yet implemented" should be self-explanatory.

**Comment by fleurc** [comment]
Ah, thank you for the answer, also yeah sure it should be but the character is a robot and i hadn't read the wiki. This is my first time playing this, i thought i had to acquire an upgrade or a new gun before getting that red cube.
