### ISSUE TITLE
Crashing GZDoom g4.4.2 -file swwmgz_m.pk3

### ISSUE THREAD

**Issue by axet** [OrdinaryMagician/swwmgz_m#6]
Hello!

gzdoom crashing with following:

gzdoom: /home/axet/Games/gzdoom/tmp/gzdoom/src/common/scripting/backend/codegen.cpp:1067: virtual ExpEmit FxFloatCast::Emit(VMFunctionBuilder*): Assertion `!from.Konst' failed.
/home/axet/bin/gzdoom: line 128: 13918 Aborted 

build:

```
cd swwmgz_m
cd fonts
./build.sh
cd ..
cd lore
./build.sh
cd ..
./pk7/mkpk3.sh

gzdoom -file swwmgz_m.pk3
```

**Comment by nicothegoat** [comment]
This seems to be a bug in GZDoom's ZScript compiler.
I managed to track down and "fix" the code that's failing to compile.
The ""fixes"" are provided in the attached patch - apply it with `git apply`.
[zscript_compiler_bug_patch.txt](https://github.com/OrdinaryMagician/swwmgz_m/files/5079221/zscript_compiler_bug_patch.txt)

**Comment by Doom2fan** [comment]
Those fixes make little sense. The fact that this works perfectly fine for other people (including the mod's author) indicates this is just a misplaced assert and works fine anyway.
The fact that you're getting asserts also means you're using a Debug build - don't do that! Debug builds should only ever be used for the specific purpose of debugging the C++ code, as they run far, far, far slower than Release builds.

**Comment by nicothegoat** [comment]
I THOUGHT I WAS ON THE RELEASFRSE BUILTG drfyhjnbdtsnynehrgh

@axet add `-DCMAKE_BUILD_TYPE=Release` when generating the build files for gzdoom

**Comment by axet** [comment]
You right, release version works

**Comment by OrdinaryMagician** [comment]
Closed, user error.
