### ISSUE TITLE
[SUGGESTION] New strings to translateable list?

### ISSUE THREAD

**Issue by Blueberryy** [OrdinaryMagician/swwmgz_m#8]
Is it possible to make these translateable?
![gzdoom_8nGhA9oJSD](https://user-images.githubusercontent.com/36592509/90342779-463bf380-e024-11ea-8d3d-217d050f85bc.png)
![gzdoom_sKxH2PK4A3](https://user-images.githubusercontent.com/36592509/90342780-476d2080-e024-11ea-8603-b1837e36e6d1.png)
![310CVAqDId](https://user-images.githubusercontent.com/36592509/90342781-4805b700-e024-11ea-9f86-603d12984498.png)
Like **%sl** or **%skm/h**

And for item sense too
![gzdoom_cDRxg7niGK](https://user-images.githubusercontent.com/36592509/90342828-a0d54f80-e024-11ea-9cd2-4e07bc4f2736.png)

**Comment by OrdinaryMagician** [comment]
Why

**Comment by Blueberryy** [comment]
Because why not? :p
